### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by MaxE1606** [Baugrube/mcbaugrube.de#1]
• Abschnitt für Plugins
  • zu größeren Plugins, Links zur jeweiligen                
Wiki und bei Plugins wie McMMo ob Sachen wie XP für die Level Standart sind und ob Skills ausgeschaltet sind etc.

**Comment by OverCrave** [comment]
Wurde gemacht, siehe die neuesten Links im Wiki ganz unten.
